backend:
  name: git-gateway
  branch: master
local_backend: true
publish_mode: editorial_workflow
media_folder: "/static/images/uploads"
public_folder: "/images/uploads"
i18n:
  structure: single_file
  locales: [zh, en]
  default_locale: zh
collections:
  - name: "menu"
    label: "選單"
    folder: "/data/menu"
    create: false
    delete: false
    slug: "{{id}}"
    fields:
      - name: "title"
        label: "名稱"
        widget: string
      - name: "id"
        label: "ID"
        widget: string
      - name: "items"
        label: "項目"
        widget: "list"
        summary: "{{fields.item}} [{{fields.style}}]"
        fields:
          - name: "item"
            label: "選單項目"
            widget: relation
            collection: "menuItems"
            search_fields: ["title", "slug"]
            value_field: "slug"
            display_fields: ["title"]
          - name: "style"
            label: "樣式"
            widget: select
            default: "primary"
            options:
              - { label: "首要", value: "primary" }
              - { label: "次要", value: "secondary" }
  - name: "menuItems"
    label: "選單項目"
    folder: "/data/menu/items"
    create: false
    delete: false
    i18n: true
    slug: "{{fields.slug}}"
    fields:
      - name: "title"
        label: "名稱"
        i18n: true
        widget: string
      - name: "slug"
        label: "Slug"
        widget: string
        pattern: ['^[a-z1-9\-]+$', "必需為英文小寫、數字或「-」組成"]
  - name: "home"
    label: "首頁"
    i18n: true
    files:
      - name: "news"
        label: "最新消息"
        i18n: true
        file: "/data/pages/home/news.yml"
        fields:
          - name: "title"
            label: "標題"
            i18n: true
            widget: string
          - name: "moreButtonTitle"
            label: "更多消息按鈕文字"
            i18n: true
            widget: string
          - name: "detailsButtonTitle"
            label: "了解更多按鈕文字"
            i18n: true
            widget: string
          - name: "items"
            label: "最新消息"
            widget: list
            summary: "{{fields.item}}"
            field:
              name: "item"
              label: "項目"
              widget: relation
              collection: "news"
              search_fields: ["title", "slug"]
              value_field: "slug"
              display_fields: ["title"]
      - name: "swiper"
        label: "幻燈片"
        file: "/data/pages/home/swiper/config.yml"
        fields:
          - name: "slides"
            label: "項目清單"
            widget: list
            summary: "{{fields.slide}}"
            field:
              name: "slide"
              label: "項目"
              widget: relation
              collection: "homeSwiperSlides"
              search_fields: ["title", "shortTitle", "slug"]
              value_field: "slug"
              display_fields: ["title"]
  - name: "homeSwiperSlides"
    label: "首頁幻燈片項目"
    slug: "{{fields.slug}}"
    i18n: true
    create: true
    folder: "/data/pages/home/swiper/slides"
    fields:
      - name: "slug"
        label: "Slug"
        widget: string
        pattern: ['^[a-z1-9\-]+$', "必需為英文小寫、數字或「-」組成"]
      - name: "shortTitle"
        label: "短標題"
        i18n: true
        widget: string
      - name: "title"
        label: "長標題"
        i18n: true
        widget: string
      - name: "subtitle"
        label: "副標題"
        i18n: true
        widget: string
      - name: "description"
        label: "介簡"
        i18n: true
        widget: text
      - name: "buttonTitle"
        label: "按鈕文字"
        i18n: true
        widget: string
        required: false
      - name: "gradient"
        label: "背景漸變"
        widget: object
        fields:
          - name: "color1"
            label: "顏色 1"
            widget: color
          - name: "color2"
            label: "顏色 2"
            widget: color
      - name: "bgImage"
        label: "圖片"
        widget: image
        media_folder: "/static/images/uploads/home/swiper/slides"
        public_folder: "/images/uploads/home/swiper/slides"
        required: false
      - name: "bgImageFillStyle"
        label: "圖片填滿"
        widget: "select"
        default:
          - "cover"
        required: false
        options:
          - label: "全填滿"
            value: "cover"
          - label: "全顯示"
            value: "contain"
  - name: "news"
    label: "最新消息"
    folder: "/data/news"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{fields.slug}}"
    i18n: true
    fields:
      - name: "title"
        label: "標題"
        i18n: true
        widget: string
      - name: "slug"
        label: "Slug"
        widget: string
        hint: "適用於網址中"
        pattern: ['^[a-z1-9\-]+$', "必需為英文小寫、數字或「-」組成"]
      - name: "date"
        label: "日期"
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        i18n: false
      - name: "category"
        label: "分類"
        widget: relation
        collection: "newsCategories"
        search_fields: ["title", "slug"]
        value_field: "slug"
        display_fields: ["title"]
        i18n: false
      - name: "content"
        label: "內容"
        i18n: true
        widget: markdown
        required: false
      - name: images
        label: "圖片"
        widget: image
        required: false
        media_library:
          config:
            multiple: true
        media_folder: "/static/images/uploads/news"
        public_folder: "/images/uploads/news"
      - name: "pdfFile"
        label: "PDF 檔案"
        i18n: true
        widget: file
        required: false
      - name: "youtubeVideoID"
        label: "YouTube 影片 ID"
        widget: string
        required: false
  - name: "newsCategories"
    label: "最新消息分類"
    folder: "/data/news/categories"
    create: true
    delete: false
    i18n: true
    slug: "{{fields.slug}}"
    sortable_fields: ["title", "slug"]
    fields:
      - name: "title"
        label: "名稱"
        i18n: true
        widget: string
      - name: "slug"
        label: "Slug"
        widget: string
        pattern: ['^[a-z1-9\-]+$', "必需為英文小寫、數字或「-」組成"]
      - name: "color"
        label: "顏色"
        widget: color
  - name: "contact"
    label: "聯絡我們"
    i18n: true
    files:
      - name: "intro"
        label: "簡介"
        i18n: true
        file: "/data/pages/contact/intro.yml"
        fields:
          - name: "title"
            label: "標題"
            i18n: true
            widget: string
          - name: "content"
            label: "內容"
            i18n: true
            widget: string
          - name: "image"
            label: "圖片"
            widget: image
      - name: "info"
        label: "聯絡資料"
        i18n: true
        file: "/data/pages/contact/info.yml"
        fields:
          - name: "title"
            label: "標題"
            i18n: true
            widget: string
          - name: "phone"
            label: "電話"
            widget: string
          - name: "fax"
            label: "傳真"
            widget: string
          - name: "email"
            label: "電郵"
            widget: string
          - name: "address"
            label: "地址"
            i18n: true
            widget: string 
  - name: "site"
    label: "全站設定"
    i18n: true
    files:
      - name: "general"
        label: "一般"
        i18n: true
        file: "/data/site/general.yml"
        fields:
          - name: "siteTitle"
            label: "網站標題"
            i18n: true
            widget: string
          - name: "socialAccounts"
            label: "社交媒體帳號"
            widget: object
            fields:
              - name: "facebook"
                label: "Facebook"
                widget: string
                hint: "URL"
              - name: "instagram"
                label: "Instagram"
                widget: string
                hint: "URL"
              - name: "youtube"
                label: "YouTube"
                widget: string
                hint: "URL"
          - name: "menuTitle"
            label: "選單按鈕文字"
            i18n: true
            widget: string
          - name: "themeSettings"
            label: "主題模式"
            widget: object
            i18n: true
            fields:
              - name: "light"
                label: "淺色"
                i18n: true
                widget: string
                hint: "按鈕文字"
              - name: "dark"
                label: "深色"
                i18n: true
                widget: string
                hint: "按鈕文字"
          - name: "copyright"
            label: "版權聲明"
            i18n: true
            widget: string
      - name: "newsletter"
        label: "電子通訊"
        i18n: true
        file: "/data/site/newsletter.yml"
        fields: 
          - name: "cta"
            label: "標語"
            i18n: true
            widget: string
          - name: "placeholder"
            label: "提示"
            i18n: true
            widget: string
          - name: "buttonTitle"
            label: "按鈕"
            i18n: true
            widget: string
